# Generated by Django 4.2.5 on 2023-09-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0005_remove_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, upload_to='category'),
        ),
    ]
